/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as DatabasesRouteImport } from './routes/databases'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as SystemsIndexRouteImport } from './routes/systems.index'
import { Route as SystemsSystemIdRouteImport } from './routes/systems.$systemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesRoute = DatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsIndexRoute = SystemsIndexRouteImport.update({
  id: '/systems/',
  path: '/systems/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSystemIdRoute = SystemsSystemIdRouteImport.update({
  id: '/systems/$systemId',
  path: '/systems/$systemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/data-sources': typeof DataSourcesRoute
  '/databases': typeof DatabasesRoute
  '/environments': typeof EnvironmentsRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/data-sources': typeof DataSourcesRoute
  '/databases': typeof DatabasesRoute
  '/environments': typeof EnvironmentsRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
  '/systems': typeof SystemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/data-sources': typeof DataSourcesRoute
  '/databases': typeof DatabasesRoute
  '/environments': typeof EnvironmentsRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/data-sources'
    | '/databases'
    | '/environments'
    | '/systems/$systemId'
    | '/systems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/data-sources'
    | '/databases'
    | '/environments'
    | '/systems/$systemId'
    | '/systems'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/data-sources'
    | '/databases'
    | '/environments'
    | '/systems/$systemId'
    | '/systems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DatabasesRoute: typeof DatabasesRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  SystemsSystemIdRoute: typeof SystemsSystemIdRoute
  SystemsIndexRoute: typeof SystemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases': {
      id: '/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DatabasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/': {
      id: '/systems/'
      path: '/systems'
      fullPath: '/systems/'
      preLoaderRoute: typeof SystemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$systemId': {
      id: '/systems/$systemId'
      path: '/systems/$systemId'
      fullPath: '/systems/$systemId'
      preLoaderRoute: typeof SystemsSystemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  DataSourcesRoute: DataSourcesRoute,
  DatabasesRoute: DatabasesRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  SystemsSystemIdRoute: SystemsSystemIdRoute,
  SystemsIndexRoute: SystemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
